version: "3"

services:
  api:
    image: dmbuddy_api:latest
    build: 
      context: ./config
      dockerfile: api.Dockerfile
    working_dir: /var/api
    env_file: ./config/api.env
    container_name: api
    networks:
      - app_net
    expose:
      - "8000"
    volumes:
      - ./app/api:/var/api/
    command: ["gunicorn", "app:app", "-c/var/gunicorn.conf.py"]
    ports:
      - "8000:8000"
  ui:
    image: dmbuddy:latest
    environment:
      - DEBUG=True
    build: 
      context: ./config
      dockerfile: ui.Dockerfile
    working_dir: /var/app
    env_file: ./config/ui.env
    container_name: app
    ports:
      - "80:3000"
    networks:
      - app_net
    volumes:
      - ./app/ui:/var/app
    command: ["gunicorn", "app:app", "-c/var/gunicorn.conf.py"]

networks:
  app_net:

